# name: Deploy Next.js App

# on:
#   push:
#     branches:
#       - main  # Run workflow on push to main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Build Next.js app
#         run: npm run build

#       - name: Copy files to server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           source: "."
#           target: "/var/www/myapps/user-frontend/Point-Australia-User-Frontend"

#       - name: Restart PM2 processes
#         uses: appleboy/ssh-action@v0.1.8
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /var/www/myapps/user-frontend/Point-Australia-User-Frontend
#             npm install
#             npm run build
#             pm2 restart next-app
#             pm2 restart backend-dev
